// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/acknowledgeMessage": {
            "post": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Removes acknowledged messages from the database for the authenticated identity. Used after a client has received and processed messages.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Acknowledge receipt of messages",
                "parameters": [
                    {
                        "description": "Message IDs to acknowledge",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.AcknowledgeMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices": {
            "get": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Returns all devices registered for push notifications for the authenticated identity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "List registered devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListDevicesResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/listMessages": {
            "post": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Returns all stored messages for the specified messageBox belonging to the authenticated identity. If the box does not exist or has no messages, an empty array is returned.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Retrieve messages from a message box",
                "parameters": [
                    {
                        "description": "Message box to list messages from",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ListMessagesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListMessagesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/permissions/get": {
            "get": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Retrieves the permission setting for a specific sender or box-wide default for the authenticated identity.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "Get a message permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the message box",
                        "name": "messageBox",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Sender's public key (omit for box-wide setting)",
                        "name": "sender",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.GetPermissionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/permissions/list": {
            "get": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Returns all permission settings for the authenticated identity, optionally filtered by message box.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "List message permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by message box name",
                        "name": "messageBox",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Maximum number of results (1-1000, default 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results to skip (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order: 'asc' or 'desc' (default 'desc')",
                        "name": "createdAtOrder",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ListPermissionsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/permissions/quote": {
            "get": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Returns fee information for sending a message to one or more recipients. Single recipient returns QuoteSingleResponse, multiple recipients returns QuoteMultiResponse.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "Get a delivery quote",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recipient public key (can be repeated for multiple recipients)",
                        "name": "recipient",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Name of the message box",
                        "name": "messageBox",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Multiple recipient quote",
                        "schema": {
                            "$ref": "#/definitions/handlers.QuoteMultiResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/permissions/set": {
            "post": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Sets fee requirements for receiving messages. Use recipientFee=0 for free, recipientFee=-1 to block, or a positive value for required payment in satoshis. Omit sender for box-wide defaults.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "Set a message permission",
                "parameters": [
                    {
                        "description": "Permission settings",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SetPermissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SetPermissionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/registerDevice": {
            "post": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Registers a device with an FCM token for receiving push notifications. Supports iOS, Android, and web platforms.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Devices"
                ],
                "summary": "Register a device for push notifications",
                "parameters": [
                    {
                        "description": "Device registration details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterDeviceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterDeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sendMessage": {
            "post": {
                "security": [
                    {
                        "BSVAuth": []
                    }
                ],
                "description": "Inserts a message into the target recipient's message box. Supports single or multiple recipients. Payment may be required depending on recipient's fee settings.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messages"
                ],
                "summary": "Send a message to recipient(s)",
                "parameters": [
                    {
                        "description": "Message to send",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SendMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SendMessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handlers.DeliveryBlockedError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.AcknowledgeMessageRequest": {
            "description": "Request to acknowledge (delete) messages",
            "type": "object",
            "properties": {
                "messageIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "handlers.DeliveryBlockedError": {
            "description": "Error response when delivery is blocked for some recipients",
            "type": "object",
            "properties": {
                "blockedRecipients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "code": {
                    "type": "string",
                    "example": "ERR_DELIVERY_BLOCKED"
                },
                "description": {
                    "type": "string",
                    "example": "Blocked recipients: 03abc..."
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "handlers.DeviceOut": {
            "description": "Device registration object",
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean",
                    "example": true
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                },
                "deviceId": {
                    "type": "string",
                    "example": "device-abc"
                },
                "fcmToken": {
                    "type": "string",
                    "example": "...abc123"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "lastUsed": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                },
                "platform": {
                    "type": "string",
                    "example": "ios"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                }
            }
        },
        "handlers.ErrorResponse": {
            "description": "Error response with status, code, and description",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "ERR_INVALID_REQUEST"
                },
                "description": {
                    "type": "string",
                    "example": "Invalid request parameters"
                },
                "status": {
                    "type": "string",
                    "example": "error"
                }
            }
        },
        "handlers.GetPermissionResponse": {
            "description": "Response containing permission details",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Permission setting found."
                },
                "permission": {
                    "$ref": "#/definitions/handlers.PermissionDetail"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.ListDevicesResponse": {
            "description": "Response containing list of devices",
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.DeviceOut"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.ListMessagesRequest": {
            "description": "Request to list messages from a message box",
            "type": "object",
            "properties": {
                "messageBox": {
                    "type": "string"
                }
            }
        },
        "handlers.ListMessagesResponse": {
            "description": "Response containing list of messages",
            "type": "object",
            "properties": {
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.MessageOut"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.ListPermissionsResponse": {
            "description": "Response containing list of permissions",
            "type": "object",
            "properties": {
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PermissionDetail"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "totalCount": {
                    "type": "integer",
                    "example": 10
                }
            }
        },
        "handlers.MessageOut": {
            "description": "Message object returned by listMessages",
            "type": "object",
            "properties": {
                "body": {
                    "type": "string",
                    "example": "{\"text\":\"Hello\"}"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                },
                "messageId": {
                    "type": "string",
                    "example": "abc123"
                },
                "sender": {
                    "type": "string",
                    "example": "03abc..."
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                }
            }
        },
        "handlers.PermissionDetail": {
            "description": "Permission details",
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                },
                "messageBox": {
                    "type": "string",
                    "example": "inbox"
                },
                "recipientFee": {
                    "type": "integer",
                    "example": 100
                },
                "sender": {
                    "type": "string",
                    "example": "03abc..."
                },
                "status": {
                    "type": "string",
                    "example": "payment_required"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2024-01-01T12:00:00.000Z"
                }
            }
        },
        "handlers.QuoteEntry": {
            "description": "Quote for one recipient in batch",
            "type": "object",
            "properties": {
                "deliveryFee": {
                    "type": "integer",
                    "example": 10
                },
                "messageBox": {
                    "type": "string",
                    "example": "inbox"
                },
                "recipient": {
                    "type": "string",
                    "example": "03abc..."
                },
                "recipientFee": {
                    "type": "integer",
                    "example": 100
                },
                "status": {
                    "type": "string",
                    "example": "payment_required"
                }
            }
        },
        "handlers.QuoteMultiResponse": {
            "description": "Response containing quotes for multiple recipients",
            "type": "object",
            "properties": {
                "blockedRecipients": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "type": "string",
                    "example": "Message delivery quotes generated for 2 recipients."
                },
                "quotesByRecipient": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.QuoteEntry"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                },
                "totals": {
                    "$ref": "#/definitions/handlers.QuoteTotals"
                }
            }
        },
        "handlers.QuoteSingle": {
            "description": "Quote for single recipient",
            "type": "object",
            "properties": {
                "deliveryFee": {
                    "type": "integer",
                    "example": 10
                },
                "recipientFee": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "handlers.QuoteSingleResponse": {
            "description": "Response containing quote for single recipient",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Message delivery quote generated."
                },
                "quote": {
                    "$ref": "#/definitions/handlers.QuoteSingle"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.QuoteTotals": {
            "description": "Totals for batch quote",
            "type": "object",
            "properties": {
                "deliveryFees": {
                    "type": "integer",
                    "example": 20
                },
                "recipientFees": {
                    "type": "integer",
                    "example": 200
                },
                "totalForPayableRecipients": {
                    "type": "integer",
                    "example": 220
                }
            }
        },
        "handlers.RegisterDeviceRequest": {
            "description": "Request to register a device for push notifications",
            "type": "object",
            "properties": {
                "deviceId": {
                    "type": "string"
                },
                "fcmToken": {
                    "type": "string"
                },
                "platform": {
                    "type": "string"
                }
            }
        },
        "handlers.RegisterDeviceResponse": {
            "description": "Response after registering a device",
            "type": "object",
            "properties": {
                "deviceId": {
                    "type": "integer",
                    "example": 1
                },
                "message": {
                    "type": "string",
                    "example": "Device registered successfully for push notifications"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.SendMessageRequest": {
            "type": "object"
        },
        "handlers.SendMessageResponse": {
            "description": "Response after sending message(s)",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Your message has been sent to 1 recipient(s)."
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SendMessageResult"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.SendMessageResult": {
            "description": "Result for a single recipient",
            "type": "object",
            "properties": {
                "messageId": {
                    "type": "string",
                    "example": "msg-123"
                },
                "recipient": {
                    "type": "string",
                    "example": "03abc..."
                }
            }
        },
        "handlers.SetPermissionRequest": {
            "description": "Request to set a permission",
            "type": "object",
            "properties": {
                "messageBox": {
                    "type": "string",
                    "example": "inbox"
                },
                "recipientFee": {
                    "type": "integer",
                    "example": 100
                },
                "sender": {
                    "type": "string",
                    "example": "03abc..."
                }
            }
        },
        "handlers.SetPermissionResponse": {
            "description": "Response after setting a permission",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Messages from sender to inbox now require 100 satoshis."
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "handlers.SuccessResponse": {
            "description": "Simple success response",
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    },
    "securityDefinitions": {
        "BSVAuth": {
            "description": "BRC-31/BRC-104 mutual authentication. Requires multiple x-bsv-auth-* headers (identity-key, nonce, signature, etc.)",
            "type": "apiKey",
            "name": "x-bsv-auth-identity-key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MessageBox Server API",
	Description:      "API for message delivery, retrieval, acknowledgement and permissions. Uses BRC-31/BRC-104 mutual authentication.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
